import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The artwork in assets/icon/ is generated by tool/make_icons_test.dart, not
/// drawn by hand.
///
/// This checks the shape of the files rather than their bytes. The generator
/// renders real text, and text rasterises differently on different platforms,
/// so a byte comparison would pass on the machine that drew them and fail
/// everywhere else. Regenerate on one machine and commit the result.
void main() {
  const expected = {
    'assets/icon/icon.png': 1024,
    'assets/icon/icon-foreground.png': 1024,
    'assets/icon/icon-monochrome.png': 1024,
    'assets/icon/splash.png': 512,
  };

  for (final entry in expected.entries) {
    group(entry.key, () {
      final file = File(entry.key);

      test('exists', () {
        expect(
          file.existsSync(),
          isTrue,
          reason: 'run: flutter test tool/make_icons_test.dart',
        );
      });

      test('is a PNG of the right size', () {
        final bytes = file.readAsBytesSync();

        // PNG magic, then the IHDR width and height as big endian uint32s at
        // a fixed offset. Enough to catch a truncated or half written file
        // without pulling in an image library.
        expect(bytes.take(8), [
          0x89,
          0x50,
          0x4E,
          0x47,
          0x0D,
          0x0A,
          0x1A,
          0x0A,
        ], reason: 'not a PNG');
        int at(int offset) =>
            (bytes[offset] << 24) |
            (bytes[offset + 1] << 16) |
            (bytes[offset + 2] << 8) |
            bytes[offset + 3];

        expect(at(16), entry.value, reason: 'width');
        expect(at(20), entry.value, reason: 'height');
      });

      test('has something drawn on it', () {
        // A blank canvas compresses to almost nothing. Anything with a board
        // and nine numbers on it does not.
        expect(
          file.lengthSync(),
          greaterThan(2000),
          reason: 'looks empty, so the render probably failed',
        );
      });
    });
  }

  test('the icon the about screen loads is declared as an asset', () {
    final pubspec = File('pubspec.yaml').readAsStringSync();
    expect(pubspec, contains('assets/icon/icon.png'));
  });
}
